<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array/>
    <key>name</key>
    <string>Java Compilation Error</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>include</key>
            <string>#arrow</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#code</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#total</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#filepath</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#linenumber</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#message</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#info</string>
        </dict>
    </array>
    <key>repository</key>
    <dict>
        <key>arrow</key>
        <dict>
            <key>match</key>
            <string>\^</string>
            <key>name</key>
            <string>storage.type.arrow</string>
        </dict>
        <key>code</key>
        <dict>
            <key>match</key>
            <string>[\t]+[^\^;]*;?</string>
            <key>name</key>
            <string>code</string>
        </dict>
        <key>filepath</key>
        <dict>
            <key>match</key>
            <string>.*(?=:\d)</string>
            <key>name</key>
            <string>comment.filepath</string>
        </dict>
        <key>info</key>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>constant.language.info</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function.info</string>
                </dict>
            </dict>
            <key>match</key>
            <string>\s+(\w+):(.*)</string>
        </dict>
        <key>linenumber</key>
        <dict>
            <key>match</key>
            <string>(?&lt;=:)\d+(?=:)</string>
            <key>name</key>
            <string>constant.numeric.linenumber</string>
        </dict>
        <key>message</key>
        <dict>
            <key>match</key>
            <string>(?&lt;=:)\s+[^:]*:.*</string>
            <key>name</key>
            <string>string.message</string>
        </dict>
        <key>total</key>
        <dict>
            <key>match</key>
            <string>^(?&lt;!:)\d+\s*[^:]+(?!:)</string>
            <key>name</key>
            <string>keyword.total</string>
        </dict>
    </dict>
    <key>scopeName</key>
    <string>source.jce</string>
    <key>uuid</key>
    <string>66494CA9-F0AC-4317-9623-E8550FA0CFF2</string>
</dict>
</plist>
