<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array/>
    <key>name</key>
    <string>Java StackTrace</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>include</key>
            <string>#trace</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#exceptionpkg</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#exceptionclass</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#message</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#url</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#quotes</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#quotesmessage</string>
        </dict>
    </array>
    <key>repository</key>
    <dict>
        <key>quotesmessage</key>
        <dict>
            <key>match</key>
            <string>[A-Z].+(?&lt;=")</string>
            <key>name</key>
            <string>constant.numeric.quotesmessage</string>
        </dict>
        <key>quotes</key>
        <dict>
            <key>match</key>
            <string>"[^"]*"</string>
            <key>name</key>
            <string>constant.numeric.quotes</string>
        </dict>
        <key>exceptionclass</key>
        <dict>
            <key>match</key>
            <string>(?&lt;=\.)\w+(?=:)</string>
            <key>name</key>
            <string>entity.name.function.class</string>
        </dict>
        <key>exceptionpkg</key>
        <dict>
            <key>match</key>
            <string>\w+\.(?=\w)</string>
            <key>name</key>
            <string>string.package</string>
        </dict>
        <key>filename</key>
        <dict>
            <key>match</key>
            <string>.*(?=:)</string>
            <key>name</key>
            <string>constant.numeric.filename</string>
        </dict>
        <key>info</key>
        <dict>
            <key>begin</key>
            <string>\(</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>keyword</string>
                </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>keyword</string>
                </dict>
            </dict>
            <key>name</key>
            <string>variable.info</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#filename</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#linenumber</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#native</string>
                </dict>
            </array>
        </dict>
        <key>linenumber</key>
        <dict>
            <key>match</key>
            <string>(?&lt;=:)\d+</string>
            <key>name</key>
            <string>storage.type.linenumber</string>
        </dict>
        <key>message</key>
        <dict>
            <key>match</key>
            <string>(?&lt;=:)\s+.*</string>
            <key>name</key>
            <string>storage.type.message</string>
        </dict>
        <key>method</key>
        <dict>
            <key>match</key>
            <string>(?&lt;=\.)(\&lt;?)\w+(\&gt;?)(\$\d+)?(?=\()</string>
            <key>name</key>
            <string>variable.parameter.method</string>
        </dict>
        <key>native</key>
        <dict>
            <key>match</key>
            <string>(?&lt;=\().*(?=\))</string>
            <key>name</key>
            <string>comment.native</string>
        </dict>
        <key>package</key>
        <dict>
            <key>match</key>
            <string>[\w]+(\$\d+)?(?=\.)</string>
            <key>name</key>
            <string>string.package</string>
        </dict>
        <key>trace</key>
        <dict>
            <key>begin</key>
            <string>(at)(\s+)</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>comment.at</string>
                </dict>
            </dict>
            <key>end</key>
            <string>^</string>
            <key>name</key>
            <string>comment.trace</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#package</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#method</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#info</string>
                </dict>
            </array>
        </dict>
        <key>url</key>
        <dict>
            <key>match</key>
            <string>(https?|ftp)://.*\w/?</string>
            <key>name</key>
            <string>comment.url</string>
        </dict>
    </dict>
    <key>scopeName</key>
    <string>source.jst</string>
    <key>uuid</key>
    <string>B12DCEFA-745E-424A-A65D-37F7B6D98013</string>
</dict>
</plist>
